repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: cargo fmt --
        args: ["--check"]
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: cargo clippy
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
