[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
common = { path = "crates/common" }
storage = {path = "crates/storage"}
thiserror = "1"
db-core = { path = "crates/db-core"}

[profile.release]
debug = true
lto = "thin"
codegen-units = 1