[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
crc32fast = "1.5.0"
db-core.workspace = true

[dev-dependencies]
tempfile = "3.10.1"
proptest = "1"
criterion = { version = "0.5", features = ["html_reports"] }
[[bench]]
name = "btree"
harness = false
